### ISSUE TITLE
Switch to `loc_tax_municipality_name` feature in `params.yaml`

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/model-condo-avm#10]
Same as the [the residential model](https://github.com/ccao-data/model-res-avm/issues/20), we need to switch to `loc_tax_municipality_name` and rerun the ingest script so that it's present in the training data.

**Comment by wrridgeway** [comment]
This has been addressed [here](https://github.com/ccao-data/model-condo-avm/commit/54870facdfd1b972f6ab8546d86c39bb50431f23#diff-f2f91cb656b58c7f581dcbdf3227f06412b648c6e0a5c10ea26e131c1eaa07e8R166).
