### ISSUE TITLE
Isolate development dependencies

### ISSUE THREAD

**Issue by jeancochrane** [ccao-data/model-condo-avm#17]
Mirror the changes from https://github.com/ccao-data/model-res-avm/pull/65 and https://github.com/ccao-data/model-res-avm/pull/66 in this repo, so that the condo model dev dependencies are also isolated and the setup step for each pipeline stage gets factored out into a shared script.

**Comment by wrridgeway** [comment]
This has been addressed [here](https://github.com/ccao-data/model-condo-avm/commit/54870facdfd1b972f6ab8546d86c39bb50431f23#diff-f2f91cb656b58c7f581dcbdf3227f06412b648c6e0a5c10ea26e131c1eaa07e8R166), though documentation sorely needs an update. I'll create a new issue for that.
