### ISSUE TITLE
Include imputed strata in assessment_data / assessment_card

### ISSUE THREAD

**Issue by Damonamajor** [ccao-data/model-condo-avm#54]
While working on [issue 31](https://github.com/ccao-data/model-condo-avm/issues/31), it was noted that the imputed strata are coded as NA in assessment_data / assessment_card.

- Are these values present in a location which I am not aware of?
- Should they be a new column or infill an existing column?
- If they fill the existing column, should there be an indicator that the values are imputed?
@dfsnow 
@wrridgeway

**Comment by dfsnow** [comment]
@Damonamajor Let's modify `02-assess` with a step that infills the missing strata for the `assessment_card` and `assessment_pin` output datasets. This would involve using the loaded recipe to `bake()` the input assessment data, probably somewhere around here: https://github.com/ccao-data/model-condo-avm/blob/master/pipeline/02-assess.R#L44. We should also add an indicator/flag column for any time the strata value is imputed.
