### ISSUE TITLE
Make model deterministic

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/model-condo-avm#61]
Work in #55 found that the subsampling used for kNN imputation in the condo model may not be deterministic. We should work to confirm that the model _is_ deterministic, and if it's not, set the appropriate seeds to make it so.

An easy way to check that the model produces the same outputs between runs is to simply `dvc repro`, then checkout the repo in a different local directory, `dvc repro` again, and diff the two `dvc.lock` files.

**Comment by ssaurbier** [comment]
Models must use a *consistent* random seed - anything else is an anti-pattern.

**Comment by dfsnow** [comment]
Seeds are already set for the entire pipeline and its various libraries. There's just one particular part of the pipeline that isn't respecting the global seed.
